package com.fap.util;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

/**
 * DerbySeed
 *
 * Generates the 55 INSERT statements for the Derby USERS table.
 *
 * This class is a standalone main() helper — it does NOT depend on
 * any ServletContext, so you can right-click it in NetBeans and
 * "Run File" without the app being deployed.
 *
 * It hard-codes the same AES algorithm that Servlets.Security uses
 * so the rows it generates are guaranteed to decrypt correctly
 * inside the running app.
 *
 * USAGE:
 *   1. Verify ENCRYPTION_KEY below matches the EncryptionKey
 *      context-param in web/WEB-INF/web.xml.
 *   2. Right-click DerbySeed.java → Run File.
 *   3. Copy the entire console output.
 *   4. Paste into NetBeans → Derby connection → Execute Command.
 *
 * Default plaintext password for every seed user is "Password123".
 */
public class DerbySeed {

    // MUST match web.xml <param-name>EncryptionKey</param-name>
    private static final String ENCRYPTION_KEY = "0bj3Ct1f!c@t1on$";

    // Default plaintext for every seed user
    private static final String DEFAULT_PW = "Password123";

    // Each row: { username, role }
    private static final String[][] SEEDS = {
        // --- 5 Admins ---
        {"admin",       "Admin"},
        {"mreyes",      "Admin"},
        {"jcruz",       "Admin"},
        {"asantos",     "Admin"},
        {"rlim",        "Admin"},

        // --- 10 Teachers ---
        {"tgarcia",     "Teacher"},
        {"mtorres",     "Teacher"},
        {"lvilla",      "Teacher"},
        {"jramos",      "Teacher"},
        {"cmendoza",    "Teacher"},
        {"pdelacruz",   "Teacher"},
        {"nagusto",     "Teacher"},
        {"eflores",     "Teacher"},
        {"rbautista",   "Teacher"},
        {"dcastro",     "Teacher"},

        // --- 40 Students ---
        {"sdomingo",    "Student"}, {"larroyo",     "Student"},
        {"amalaba",     "Student"}, {"jfernandez",  "Student"},
        {"eortiz",      "Student"}, {"cbalan",      "Student"},
        {"rvalen",      "Student"}, {"mlopez",      "Student"},
        {"hperez",      "Student"}, {"vsilva",      "Student"},
        {"fjavier",     "Student"}, {"amorales",    "Student"},
        {"jrosario",    "Student"}, {"rfajardo",    "Student"},
        {"cnavarro",    "Student"}, {"btan",        "Student"},
        {"mochoa",      "Student"}, {"rgallego",    "Student"},
        {"lsantiago",   "Student"}, {"jvargas",     "Student"},
        {"panonuevo",   "Student"}, {"mdiaz",       "Student"},
        {"sgutier",     "Student"}, {"jaquino",     "Student"},
        {"cdimaano",    "Student"}, {"rmagsino",    "Student"},
        {"apangili",    "Student"}, {"ksalvador",   "Student"},
        {"mreyes2",     "Student"}, {"jjavella",    "Student"},
        {"grosales",    "Student"}, {"isandoval",   "Student"},
        {"rmacapag",    "Student"}, {"atorre",      "Student"},
        {"lcabrera",    "Student"}, {"mtolentino",  "Student"},
        {"cdyon",       "Student"}, {"rmanansa",    "Student"},
        {"vapostol",    "Student"}, {"jrodriguez",  "Student"}
    };

    public static void main(String[] args) throws Exception {
        String encrypted = encrypt(DEFAULT_PW);

        System.out.println("-- ============================================================");
        System.out.println("-- Auto-generated by com.fap.util.DerbySeed");
        System.out.println("-- Plaintext password for every user: " + DEFAULT_PW);
        System.out.println("-- AES key used:  " + ENCRYPTION_KEY);
        System.out.println("-- Total users:   " + SEEDS.length);
        System.out.println("-- ============================================================");
        System.out.println();

        for (String[] row : SEEDS) {
            String user = row[0];
            String role = row[1];
            System.out.printf(
                "INSERT INTO USERS (USERNAME, PASSWORD, USERROLE) VALUES ('%s', '%s', '%s');%n",
                user, encrypted, role);
        }

        System.out.println();
        System.out.println("-- Done. " + SEEDS.length + " rows generated.");
    }

    // ----------------------------------------------------------------
    // Same AES/ECB/PKCS5Padding logic as Servlets.Security.Encrypt()
    // duplicated here so this utility runs WITHOUT a ServletContext.
    // ----------------------------------------------------------------
    private static String encrypt(String plain) throws Exception {
        byte[] key = ENCRYPTION_KEY.getBytes(StandardCharsets.UTF_8);
        if (key.length != 16) {
            throw new IllegalStateException("EncryptionKey must be exactly 16 bytes. "
                    + "Current length: " + key.length);
        }
        Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key, "AES"));
        byte[] encrypted = cipher.doFinal(plain.getBytes(StandardCharsets.UTF_8));
        return Base64.getEncoder().encodeToString(encrypted);
    }
}
