package com.fap.report;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

/**
 * PageNumberEventHandler
 *
 * iText page event helper that draws:
 *   - the report HEADER (from web.xml) at the top of every page
 *   - the report FOOTER (from web.xml) at the bottom
 *   - "Page X of Y" on every page
 *   - the username of the logged-in user
 *   - the generation date/time
 *
 * Y (total pages) is rendered using a PdfTemplate that is filled in on close().
 * This is the standard iText 5 pattern for "Page X of Y."
 */
public class PageNumberEventHandler extends PdfPageEventHelper {

    private final String header;       // from web.xml report.header
    private final String footer;       // from web.xml report.footer
    private final String username;     // who generated this report
    private final String generatedAt;  // formatted timestamp

    private PdfTemplate totalPagesTpl;
    private BaseFont    baseFont;

    private static final Font HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.BLACK);
    private static final Font FOOTER_FONT = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.DARK_GRAY);
    private static final Font META_FONT   = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.DARK_GRAY);

    public PageNumberEventHandler(String header, String footer, String username, String generatedAt) {
        this.header      = header   != null ? header   : "";
        this.footer      = footer   != null ? footer   : "";
        this.username    = username != null ? username : "Unknown";
        this.generatedAt = generatedAt;
    }

    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {
        // Reserve a small template that will hold the total page count.
        totalPagesTpl = writer.getDirectContent().createTemplate(40, 12);
        try {
            baseFont = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load BaseFont", e);
        }
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfContentByte cb = writer.getDirectContent();
        Rectangle pageSize = document.getPageSize();

        // -------- HEADER (from web.xml) --------
        ColumnText.showTextAligned(
                cb, Element.ALIGN_CENTER,
                new Phrase(header, HEADER_FONT),
                (pageSize.getLeft() + pageSize.getRight()) / 2f,
                pageSize.getTop() - 25,
                0);

        // Meta line — left side under header
        ColumnText.showTextAligned(
                cb, Element.ALIGN_LEFT,
                new Phrase("Generated by: " + username, META_FONT),
                pageSize.getLeft() + 36,
                pageSize.getTop() - 42,
                0);

        // Meta line — right side under header
        ColumnText.showTextAligned(
                cb, Element.ALIGN_RIGHT,
                new Phrase("Generated on: " + generatedAt, META_FONT),
                pageSize.getRight() - 36,
                pageSize.getTop() - 42,
                0);

        // -------- FOOTER (from web.xml) --------
        ColumnText.showTextAligned(
                cb, Element.ALIGN_CENTER,
                new Phrase(footer, FOOTER_FONT),
                (pageSize.getLeft() + pageSize.getRight()) / 2f,
                pageSize.getBottom() + 25,
                0);

        // -------- PAGE X OF Y (bottom right) --------
        int currentPage = writer.getPageNumber();
        String pageText = "Page " + currentPage + " of ";
        float textBase  = pageSize.getBottom() + 12;
        float textWidth = baseFont.getWidthPoint(pageText, 9);

        ColumnText.showTextAligned(
                cb, Element.ALIGN_RIGHT,
                new Phrase(pageText, FOOTER_FONT),
                pageSize.getRight() - 36 - 40,
                textBase,
                0);

        // Place the template that will be filled with total page count
        cb.addTemplate(totalPagesTpl, pageSize.getRight() - 36 - 40, textBase);
    }

    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {
        // Fill in the total page count placeholder on every page
        totalPagesTpl.beginText();
        totalPagesTpl.setFontAndSize(baseFont, 9);
        totalPagesTpl.setTextMatrix(0, 0);
        totalPagesTpl.showText(String.valueOf(writer.getPageNumber()));
        totalPagesTpl.endText();
    }
}
